# Generated by Django 5.1.2 on 2024-10-16 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('batter_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pitcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pitcher_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matchup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('launch_angle', models.FloatField()),
                ('exit_speed', models.FloatField()),
                ('hit_distance', models.FloatField()),
                ('hang_time', models.FloatField()),
                ('hit_spin_rate', models.FloatField()),
                ('batter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchups.batter')),
                ('pitcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchups.pitcher')),
            ],
        ),
    ]
